name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      PUBLIC_SANITY_PROJECT_ID: 'jac4tgqn'
      PUBLIC_SANITY_DATASET: 'production'
      PUBLIC_SANITY_STUDIO_URL: 'https://postey.sanity.studio'
      PUBLIC_ENABLE_DEBUG: 'false'
      SANITY_VIEWER_TOKEN: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Format code (if needed)
        run: yarn format

      - name: Run Svelte type checking
        run: yarn run check

      - name: Run linting and formatting checks
        run: yarn lint

      - name: Run unit tests
        run: yarn test:unit

      - name: Install Playwright browsers
        if: github.ref == 'refs/heads/main'
        run: yarn playwright install --with-deps

      - name: Run end-to-end tests
        if: github.ref == 'refs/heads/main'
        run: yarn test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30
